# Sample config file

# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  error_border: "243, 139, 168" # error dialog border is Red
  error_text: "235, 160, 172" # error message text (e.g. "Spotify API reported error 404") is Maroon
  hint: "249, 226, 175" # hint text in errors Yellow
  playbar_background: "17, 17, 27" # background of progress bar "Crust"
  playbar_progress: "24, 24, 37" # filled-in part of the progress bar Mantle
  playbar_progress_text: "250, 179, 135" # song length and time played/left indicator in the progress bar "Green"
  playbar_text: "166, 173, 200" # artist name in player pane is "Subtext 0"
  inactive: "108, 112, 134" # borders of inactive panes "Overlay 0"
  text: "205, 214, 244" # text in panes is "Text"
  active: "243, 139, 168" # current playing song in list Mauve
  banner: "250, 179, 135" # the "spotify-tui" banner on launch Teal
  hovered: "249, 226, 175" # hovered pane border Pink
  selected: "250, 179, 135" # a) selected pane border, b) hovered item in list, & c) track title in player Lavender
  header: "249, 226, 175" # header text in panes (e.g. 'Title', 'Artist', etc.) Lavender

behavior:
  seek_milliseconds: 5000
  volume_increment: 5
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 250
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: true
  # Controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
  # Disables the responsive layout that makes the search bar smaller on bigger
  # screens and enforces a wide search bar
  enforce_wide_search_bar: false
  set_window_title: true

keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "ctrl-q"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "="
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "ctrl-s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
